const express = require('express')
const morgan = require('morgan')
const personnagesRoutes = require('./routes/personnages')
const usersRoutes = require('./routes/user')
const sequelize = require('./db/sequelize')
const sequelizeSession = require('./db/sessionSequelize')
const app = express()


app.use(morgan('dev'))
app.use('/api/personnages',personnagesRoutes)
app.use('/api/auth',usersRoutes)
app.use('/images',express.static('images'))
sequelize.initialisationConnexionBdd()
sequelizeSession.init()
app.listen(3000,console.log(`Le serveur a bien démarrer sur le port 3000 !`))