const express = require('express')
const morgan = require('morgan')
const personnagesRoutes = require('./routes/personnages')
const sequelize = require('./db/sequelize')
const app = express()

app.use(morgan('dev'))
app.use('api/personnages',personnagesRoutes)
sequelize.initialisationConnexionBdd()
app.listen(3000,console.log(`Le serveur a bien démarrer sur le port 3000 !`))